# Generated by Django 2.2.14 on 2020-12-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20201214_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
