# Generated by Django 2.2.14 on 2020-12-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20201214_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
