# Generated by Django 2.2.14 on 2020-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(height_field=True, upload_to='', width_field=True)),
                ('meta', models.CharField(max_length=30)),
                ('frequency', models.IntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
