# Generated by Django 2.2.14 on 2020-12-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
